### PR TITLE
✨ added several services

### PR DESCRIPTION
**Pull request by criation**
Neu hinzugefügter Service https://crater.financial/, für alle Fälle dass sich jemand Selbstständig machen, rich werden will oder einfach neugierig ist

### CODE REVIEW

**Comment by criation** [comment]
Neu hinzugefügter Service: https://github.com/MauriceNino/dashdot, Für den Fall, dass ihr euren Server Stylisch beim Schlafen zusehen wollt ;)

**Comment by criation** [comment]
[Verse 1]
Am I still waiting
For this merge to come?
No need to panic,
Hoping for an "Accepted"

[Pre-Chorus]
I'm waiting, like on burning coals,
Yet your response remains hidden.
You could sweeten my day,
With the merge button to unchain.

[Chorus]
These lines, full of expectation,
No rejection, no deviation,
So, what would you tell me?
It's time to pull it in!

[Verse 2]
Am I still waiting
For this merge to come?
No need to panic,
Hoping for an "Accepted"

[Pre-Chorus]
I'm waiting, like on burning coals,
Yet your response remains hidden.
You could sweeten my day,
With the merge button to unchain.

[Chorus]
These lines, full of expectation,
No rejection, no deviation,
So, what would you tell me?
It's time to pull it in!

[Bridge]
Am I still waiting
For this merge to come?

[Chorus]
No need to panic, no need to doubt,
Just one click, and the waiting is out.
No need to panic, no need to doubt,
Let's merge the code, that's what it's about!

[Outro]
No need to panic, no need to doubt,
Let's merge the code, that's what it's about!
No need to panic, no need to doubt,
Let's merge the code, that's what it's about!

https://www.youtube.com/watch?v=qO-mSLxih-c

**Comment by JulianKropp** [comment]
# crater
I tried to make it work for around 3 hours. Sorry but it doesn't work.

When I start it I got some errors:
Browser:
```
Warning: require(/var/www/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/public/index.php on line 28

Fatal error: Uncaught Error: Failed opening required '/var/www/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/public/index.php:28 Stack trace: #0 {main} thrown in /var/www/public/index.php on line 28
```

Logs:
```
crater-app    | 192.168.32.2 -  14/Dec/2023:20:35:50 +0000 "GET /index.php" 200
crater-nginx  | 172.0.0.8 - - [14/Dec/2023:20:35:50 +0000] "GET / HTTP/1.1" 200 465 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"
crater-app    | 192.168.32.2 -  14/Dec/2023:20:35:51 +0000 "GET /index.php" 200
crater-nginx  | 172.0.0.8 - - [14/Dec/2023:20:35:52 +0000] "GET / HTTP/1.1" 200 465 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"
crater-nginx  | 172.0.0.8 - - [14/Dec/2023:20:35:53 +0000] "GET / HTTP/1.1" 200 465 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"
crater-app    | 192.168.32.2 -  14/Dec/2023:20:35:53 +0000 "GET /index.php" 200
crater-cron   | 
crater-cron   | Warning: require(/var/www/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/artisan on line 18
crater-cron   | 
crater-cron   | Fatal error: Uncaught Error: Failed opening required '/var/www/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/artisan:18
crater-cron   | Stack trace:
crater-cron   | #0 {main}
crater-cron   |   thrown in /var/www/artisan on line 18
```

**Comment by JulianKropp** [comment]
# homarr

image

**Comment by JulianKropp** [comment]
# dash
I will not accept dash. This looks like a huge security risk. I know its read only. But mounting the hole root folder with all data is too much
```
-v /:/mnt/host:ro \
```

**Pull request merged**
